steps:
  - id: Install
    name: ghcr.io/astral-sh/uv:python3.14-bookworm-slim
    entrypoint: uv
    args: [sync, --frozen]

  - id: Test
    name: ghcr.io/astral-sh/uv:python3.14-bookworm-slim
    entrypoint: uv
    args: [run, pytest]

  - id: Build
    name: gcr.io/cloud-builders/docker
    args: [build, -t, "${_IMAGE}:latest", .]

  - id: Push
    name: gcr.io/cloud-builders/docker
    args: [push, "${_IMAGE}:latest"]

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
substitutions:
  _IMAGE: europe-west6-docker.pkg.dev/$PROJECT_ID/pe-a-atl1/pe-a-atl1
